### PR TITLE
Icon, logo and extension name changes

### PR DESCRIPTION
**Pull request by bukitoka**
Hi, I just update activity bar icon to follow vscode icon design and update the logo and the extension name to prevent ambiguous thing. With a clear name and logo I think it can improve the extension popularity. 

Screenshot (477)

### CODE REVIEW

**Comment by cweijan** [comment]
Thanks, but in fact I have released an extension called Database Client, but I haven’t got a lot of installations.

**Comment by cweijan** [comment]
The new container icon does not look good, I want to switch to the old one, but the logo is great。
image

**Comment by bukitoka** [comment]
ah okayy, I will learn the source code and contribute on another issue

**Comment by cweijan** [comment]
Hi, are you still using this extension? I have enabled the pay system in the new version, to thank you for making the icon, I will give you two years of premium.

**Comment by bukitoka** [comment]
hello @cweijan, yes I still use it. Thanks for your appreciation!

**Comment by cweijan** [comment]
Sign up for an account at https://database-client.com/#/, tell me your email, or send it to support@database-client.com.

**Pull request merged**
