### PR TITLE
⏳ [DEV]

### PR DESCRIPTION
**Pull request by itsdonnix**

### CODE REVIEW

**Comment by itsdonnix** [comment]
@cweijan Please review 🙌

**Comment by cweijan** [comment]
Keyword maximum is five.

**Comment by itsdonnix** [comment]
Ahh... will revert it then 😬

**Comment by cweijan** [comment]
And I don't change extension name, database client will publish as new extension, mysql will saved.

**Comment by itsdonnix** [comment]
I think you must separate it to another repo. Then archive the `vscode-mysql` or something

**Comment by itsdonnix** [comment]
Though its just a display name. So revert it?

**Pull request closed without merging**
