### PR TITLE
UI & UX Improvements

### PR DESCRIPTION
**Pull request by itsdonnix**

### CODE REVIEW

**Comment by cweijan** [comment]
Hi sir, thank you for your contribution, but note that the extension is now closed source, and the source code of this repository is no longer updated.

**Comment by itsdonnix** [comment]
Hi @cweijan... 

No problem, any change to get merged?

**Comment by cweijan** [comment]
SqlServer cannot be directly changed to SQL Server, the extension can only recognize SqlServer.

**Comment by itsdonnix** [comment]
Alright.. I shouldn't change that. Just revert it. I still working consistent spacing on the connect page. Wil push tomorrow

**Comment by cweijan** [comment]
Thanks.

**Pull request merged**
